"""empty message

Revision ID: f9b232f0cc2c
Revises: b7665367d66b
Create Date: 2018-08-31 23:18:05.003938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b232f0cc2c'
down_revision = 'b7665367d66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mission', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission', sa.Column('content', sa.VARCHAR(length=250), nullable=True))
    # ### end Alembic commands ###
